### PR TITLE
Create wish.ride

### PR DESCRIPTION
**Pull request by gingerabsurdity**
this asset can be burned only at 11:11 am also it can be sent by anyone or reissued/changed by the issuer

### CODE REVIEW

**Comment by KardanovIR** [comment]
Seems like using timestamp is not a good idea for smart contracts, because timestamp of transaction may differ by up to 90 minutes from a real timestamp. It means I can send a transaction at any time.

**Comment by KardanovIR** [comment]
@petermz @ismagin guys, what do you think about using this contract as an example? Isn't it a bad practice to use a timestamp?

**Comment by petermz** [comment]
It is indeed gameable, but not necessarily bad -- for this particular contract it's ok, more or less. Maybe just put a comment in the contract explaining the matter.

**Comment by ismagin** [comment]
I think it would be a misleading example.
One can rely on timestamp as cooldown time or whatnot.
We even had an idea to remove ts from tx

**Pull request closed without merging**
